coverage:
  status:
    project:
      default:
        target: 80%
        if_ci_failed: error
        flags:
          - unit-tests
    patch:
      default:
        target: 100%
flags:
  unit-tests:
    paths:
      - src/
    carryforward: true