coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
        flags:
          - unit-tests
    patch:
      default:
        target: 100%
flags:
  unit-tests:
    paths:
      - src/
    carryforward: true
codecov:
  notify:
    wait_for_ci: false