# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Inclusive Language Extension For Sonarqube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

jobs:
  run-unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2.
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: maven
      - name: Run Unit test
        run: |
          mvn clean test -q

  generate-version8:
    name: Generate Version 8
    runs-on: ubuntu-20.04
    needs: run-unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2.
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: maven
      - name: "Generate Package version: 8"
        run: |
          mvn clean package -DskipTests
      - uses: actions/upload-artifact@v2
        with:
          name: ext-its-v8
          path: target/vmw-its-scanner*.jar

  generate-version79:
    name: Generate Version 7.9
    runs-on: ubuntu-20.04
    needs: run-unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2.
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: maven
      - name: "Generate Package version: 7.9"
        run: |
          mvn -f pom-7.9.xml clean package -DskipTests
      - uses: actions/upload-artifact@v2
        with:
          name: ext-its-v7.9
          path: target/vmw-its-scanner*.jar